[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Alex Hamilton <alex.hamilton@ou.edu>"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "advent"
path = "src/main.rs"

[dependencies]
clap = "2.32.0"
